### ISSUE TITLE
retained messages not fetched on sub

### ISSUE THREAD

**Issue by sperfect** [jooink/gwt-mqtt#1]
When subscribing to a topic the retained messages is not fetched on subscription.

Great work, by the way

**Comment by jooink** [comment]
Hi, thanks.

Do you know if paho has the same problem ?

Aleberto

**Comment by sperfect** [comment]
Hello,
Checked with http://www.hivemq.com/demos/websocket-client/
It works with paho.js (http://www.hivemq.com/full-featured-mqtt-client-browser/)
It does get the retained message on subscription.

Stelios

**Comment by abmancini** [comment]
Seems that the problem was in the sample app not in the library.
We were adding the message handler after actual subscription causing loss of
retained messages. 

Should be solved. Please check if you can. 

BTW, I upgraded the used paho javascript client too.

**Comment by sperfect** [comment]
Great.
Suspected so, but I am just getting used with GWT.
